
### API SUPPLIERS

### CREATE SUPPLIER
POST http://localhost:3000/suppliers
Content-Type: application/json

{
    "name" : "amat",
    "email" : "amat@gmail.com",
    "address" : "pekanbaru"
}

### GET ALL SUPPLIER
GET  http://localhost:3000/suppliers

### GET BY ID SUPPLIER
GET  http://localhost:3000/suppliers/2

### UPDATE SUPPLIER
PUT  http://localhost:3000/suppliers/1
Content-Type: application/json

{
    "address" : "bengkalis"
}

### DELETE SUPPLIER
DELETE http://localhost:3000/suppliers/2
Content-Type: application/json



### API PRODUCTS

### CREATE PRODUCT
POST http://localhost:3000/products
Content-Type: application/json

{
    "name" : "samsung",
    "quantity" : 20
}

### GET ALL PRODUCT
GET  http://localhost:3000/products

### GET PRODUCT BY ID
GET  http://localhost:3000/products/3

### UPDATE PRODUCT
PUT  http://localhost:3000/products/1
Content-Type: application/json

{
    "quantity" : 32
}

### DELETE PRODUCT
DELETE http://localhost:3000/products/2
Content-Type: application/json



### API COMPONENTS

### CREATE COMPONENT
POST http://localhost:3000/components
Content-Type: application/json

{
    "name" : "lcd",
    "description" : "ini adalah lcdku"
}

### GET ALL COMPONENT
GET  http://localhost:3000/components

### GET COMPONENT BY ID
GET  http://localhost:3000/components/4

### UPDATE COMPONENT
PUT  http://localhost:3000/components/1
Content-Type: application/json

{
    "description" : "ini adalah lcd samsung"
}

### DELETE COMPONENTD
DELETE http://localhost:3000/components/1
Content-Type: application/json